server:
  port: 8535

jdbc_test:
  driverClass: com.mysql.jdbc.Driver
  JdbcUrl: jdbc:mysql://localhost:3306/test
  User: root
  Password: 123456

spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
mybatis:
  typeAliasesPackage: com.demo
  mapperLocations: classpath:/sqlmapper/*.xml
  configLocation: classpath:/mybatis-config.xml
