server:
  port: 8535

jdbc_test:
  driverClass: com.mysql.jdbc.Driver
  JdbcUrl: jdbc:mysql://localhost:3306/test
  User: root
  Password: 123456

spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
  cache:
    type: redis
  application:
    name: spirng-boot-rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

mybatis:
  typeAliasesPackage: com.demo
  mapperLocations: classpath:/sqlmapper/*.xml
security:
  user:
    name: admin
    password: admin

my:
  config: hehehe